name: RSpec workflow
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        env:
          RAILS_ENV: test
          COVERAGE: false

      - name: Run RSpec
        run: bundle exec rspec  --require rails_helper
        env:
          RAILS_ENV: test
          COVERAGE: true
